const employees = [
  {
    id: 1,
    first_name: "Emily",
    last_name: "Smith",
    email: "emilysmith@example.com",
    gender: "female",
    age: 32,
  },
  {
    id: 2,
    first_name: "Jacob",
    last_name: "Johnson",
    email: "jacobjohnson@example.com",
    gender: "male",
    age: 45,
  },
  {
    id: 3,
    first_name: "Ava",
    last_name: "Williams",
    email: "avawilliams@example.com",
    gender: "female",
    age: 28,
  },
  {
    id: 4,
    first_name: "Liam",
    last_name: "Jones",
    email: "liamjones@example.com",
    gender: "male",
    age: 36,
  },
  {
    id: 5,
    first_name: "Olivia",
    last_name: "Brown",
    email: "oliviabrown@example.com",
    gender: "female",
    age: 50,
  },
  {
    id: 6,
    first_name: "Noah",
    last_name: "Garcia",
    email: "noahgarcia@example.com",
    gender: "male",
    age: 22,
  },
  {
    id: 7,
    first_name: "Sophia",
    last_name: "Martinez",
    email: "sophiamartinez@example.com",
    gender: "female",
    age: 41,
  },
  {
    id: 8,
    first_name: "Ethan",
    last_name: "Robinson",
    email: "ethanrobinson@example.com",
    gender: "male",
    age: 33,
  },
  {
    id: 9,
    first_name: "Isabella",
    last_name: "Clark",
    email: "isabellaclark@example.com",
    gender: "female",
    age: 29,
  },
  {
    id: 10,
    first_name: "Mason",
    last_name: "Rodriguez",
    email: "masonrodriguez@example.com",
    gender: "male",
    age: 47,
  },
  {
    id: 11,
    first_name: "Amelia",
    last_name: "Lewis",
    email: "amelialewis@example.com",
    gender: "female",
    age: 36,
  },
  {
    id: 12,
    first_name: "Logan",
    last_name: "Lee",
    email: "loganlee@example.com",
    gender: "male",
    age: 55,
  },
  {
    id: 13,
    first_name: "Evelyn",
    last_name: "Walker",
    email: "evelynwalker@example.com",
    gender: "female",
    age: 25,
  },
  {
    id: 14,
    first_name: "James",
    last_name: "Hall",
    email: "jameshall@example.com",
    gender: "male",
    age: 38,
  },
  {
    id: 15,
    first_name: "Harper",
    last_name: "Perez",
    email: "harperperez@example.com",
    gender: "female",
    age: 30,
  },
  {
    id: 16,
    first_name: "Lucas",
    last_name: "Young",
    email: "lucasyoung@example.com",
    gender: "male",
    age: 43,
  },
  {
    id: 17,
    first_name: "Charlotte",
    last_name: "Evans",
    email: "charlotteevans@example.com",
    gender: "female",
    age: 34,
  },
  {
    id: 18,
    first_name: "Benjamin",
    last_name: "King",
    email: "benjaminking@example.com",
    gender: "male",
    age: 39,
  },
  {
    id: 19,
    first_name: "Avery",
    last_name: "Wright",
    email: "averywright@example.com",
    gender: "female",
    age: 27,
  },
  {
    id: 20,
    first_name: "Mia",
    last_name: "Lopez",
    email: "mialopez@example.com",
    gender: "female",
    age: 31,
  },
  {
    id: 21,
    first_name: "Daniel",
    last_name: "Hill",
    email: "danielhill@example.com",
    gender: "male",
    age: 42,
  },
  {
    id: 22,
    first_name: "Abigail",
    last_name: "Scott",
    email: "abigailscott@example.com",
    gender: "female",
    age: 37,
  },
  {
    id: 23,
    first_name: "Jackson",
    last_name: "Green",
    email: "jacksongreen@example.com",
    gender: "male",
    age: 49,
  },
  {
    id: 24,
    first_name: "Chloe",
    last_name: "Adams",
    email: "chloeadams@example.com",
    gender: "female",
    age: 22,
  },
  {
    id: 25,
    first_name: "Samuel",
    last_name: "Baker",
    email: "samuelbaker@example.com",
    gender: "male",
    age: 24,
  },
  {
    id: 26,
    first_name: "Grace",
    last_name: "Gonzalez",
    email: "gracegonzalez@example.com",
    gender: "female",
    age: 26,
  },
  {
    id: 27,
    first_name: "Henry",
    last_name: "Nelson",
    email: "henrynelson@example.com",
    gender: "male",
    age: 57,
  },
  {
    id: 28,
    first_name: "Luna",
    last_name: "Carter",
    email: "lunacarter@example.com",
    gender: "female",
    age: 44,
  },
  {
    id: 29,
    first_name: "Alexander",
    last_name: "Parker",
    email: "alexanderparker@example.com",
    gender: "male",
    age: 35,
  },
  {
    id: 30,
    first_name: "Stella",
    last_name: "Torres",
    email: "stellatorres@example.com",
    gender: "female",
    age: 29,
  },
  {
    id: 31,
    first_name: "William",
    last_name: "Harris",
    email: "williamharris@example.com",
    gender: "male",
    age: 53,
  },
  {
    id: 32,
    first_name: "Nova",
    last_name: "Murphy",
    email: "novamurphy@example.com",
    gender: "female",
    age: 39,
  },
  {
    id: 33,
    first_name: "Michael",
    last_name: "Rivera",
    email: "michaelrivera@example.com",
    gender: "male",
    age: 31,
  },
  {
    id: 34,
    first_name: "Penelope",
    last_name: "Cooper",
    email: "penelopecooper@example.com",
    gender: "female",
    age: 26,
  },
  {
    id: 35,
    first_name: "Elijah",
    last_name: "Reed",
    email: "elijahreed@example.com",
    gender: "male",
    age: 41,
  },
  {
    id: 36,
    first_name: "Aria",
    last_name: "Gomez",
    email: "ariagomez@example.com",
    gender: "female",
    age: 23,
  },
  {
    id: 37,
    first_name: "David",
    last_name: "Kelly",
    email: "davidkelly@example.com",
    gender: "male",
    age: 48,
  },
  {
    id: 38,
    first_name: "Elena",
    last_name: "Bailey",
    email: "elenabailey@example.com",
    gender: "female",
    age: 29,
  },
  {
    id: 39,
    first_name: "Carter",
    last_name: "Howard",
    email: "carterhoward@example.com",
    gender: "male",
    age: 37,
  },
  {
    id: 40,
    first_name: "Aaliyah",
    last_name: "Ward",
    email: "aaliyahward@example.com",
    gender: "female",
    age: 25,
  },
  {
    id: 41,
    first_name: "Joseph",
    last_name: "Cook",
    email: "josephcook@example.com",
    gender: "male",
    age: 47,
  },
  {
    id: 42,
    first_name: "Nora",
    last_name: "Morales",
    email: "noramorales@example.com",
    gender: "female",
    age: 28,
  },
  {
    id: 43,
    first_name: "Eli",
    last_name: "Sanders",
    email: "elisanders@example.com",
    gender: "male",
    age: 36,
  },
  {
    id: 44,
    first_name: "Alice",
    last_name: "Bennett",
    email: "alicebennett@example.com",
    gender: "female",
    age: 39,
  },
  {
    id: 45,
    first_name: "Mateo",
    last_name: "Richardson",
    email: "mateorichardson@example.com",
    gender: "male",
    age: 33,
  },
  {
    id: 46,
    first_name: "Ruby",
    last_name: "Gray",
    email: "rubygray@example.com",
    gender: "female",
    age: 32,
  },
  {
    id: 47,
    first_name: "Levi",
    last_name: "Wood",
    email: "leviwood@example.com",
    gender: "male",
    age: 56,
  },
  {
    id: 48,
    first_name: "Camila",
    last_name: "James",
    email: "camilajames@example.com",
    gender: "female",
    age: 27,
  },
  {
    id: 49,
    first_name: "Luke",
    last_name: "Foster",
    email: "lukefoster@example.com",
    gender: "male",
    age: 40,
  },
  {
    id: 50,
    first_name: "Layla",
    last_name: "Russell",
    email: "laylarussell@example.com",
    gender: "female",
    age: 30,
  },
];

export default employees;
